name: Deploy-to-EC2

on:
  push:
    branches:
      - v1

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./target/*.jar"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/target/, /src/, **.env, rebuild_app.sh, watcher.sh"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Start application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.TARGET_DIR }}
            java -jar *.jar # Executa o JAR gerado
          EOF

      - name: Notify on success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Deploy feito com sucesso! 🎉"}' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Pipeline falhou! 😞"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
